apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    app: hello
spec:
  containers:
  - name: hello-container
    image: europe-west1-docker.pkg.dev/qwiklabs-gcp-03-366b213e3043/my-repo/hello:latest
    ports:
    - containerPort: 8080
    env:
    - name: PORT
      value: "8080"